const text10 = 'Lorem ipsum dolor sit amet consectetur adipiscing elit Phasellus vitae arcu viverra dapibus tellus vitae dictum tortor Sed suscipit sapien et urna volutpat mattis tempor nulla mollis Curabitur eu pharetra orci Integer sed posuere mi eu sagittis nisi Pellentesque id semper felis nec commodo dolor Maecenas ante nulla rhoncus at maximus id sodales eget dolor Vestibulum ligula libero molestie ut lorem ac tempus tincidunt nisi Phasellus mattis facilisis nibh id imperdiet Praesent ullamcorper convallis pretium Fusce ex quam semper a orci eget pharetra elementum purus Pellentesque convallis vulputate orci ut efficitur Sed justo massa bibendum ut facilisis sit amet tempus vel dui Sed convallis scelerisque pulvinar Fusce aliquet nibh ac gravida interdum Sed pellentesque lectus non risus sollicitudin ac lacinia ante mollis Cras in augue vestibulum massa tincidunt congue at et dolor Suspendisse eget lorem ut velit maximus porttitor at eu odio Donec mauris ex aliquet et sapien at mollis lacinia arcu Suspendisse fermentum quam eu consectetur posuere Proin hendrerit odio augue nec venenatis metus tristique ac Nam non convallis arcu Sed et lorem tortor Pellentesque vitae ipsum ex Vivamus quam risus semper a pharetra nec ornare nec lorem Vestibulum euismod mauris pharetra commodo tortor id interdum mauris';
console.log(splitTextIntoSMS(text10));

const text1 = 'Lorem ipsum dolor sit amet consectetur adipiscing elit';
console.log(splitTextIntoSMS(text1));

const text2 = 'Lorem ipsum dolor sit amet consectetur adipiscing elit Nullam eleifend odio at magna pretium suscipit Nam commodo mauris felis ut suscipit velit efficitur eget Sed sit amet posuere risus';
console.log(splitTextIntoSMS(text2));

const text7 = 'Lorem ipsum dolor sit amet consectetur adipiscing elit Sed sem orci sodales id rhoncus at laoreet sit amet purus Nulla fringilla mauris non mattis mattis Sed molestie sapien nibh ac pretium nisi congue quis Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas Aenean feugiat eros cursus purus vehicula lacinia Duis facilisis ante a sollicitudin interdum Praesent tempus posuere lorem sit amet venenatis turpis rutrum eget Phasellus finibus nec risus ut auctor Duis pharetra ipsum leo sit amet eleifend nulla suscipit in Sed sit amet fermentum metus Vivamus scelerisque scelerisque felis fringilla ullamcorper sapien efficitur nec Vestibulum nec enim ultrices tempus odio ac sodales ligula Etiam sollicitudin lacus eget odio condimentum tempus Nullam vel tincidunt metus nullam';
console.log(splitTextIntoSMS(text7));